artifact_location: file:///C:/Users/ma2mo/Documents/Master/vision/Trabajo-final/UDIT-main/UDIT-main/runs/mlflow/342124807985113997
creation_time: 1747854309967
experiment_id: '342124807985113997'
last_update_time: 1747854309967
lifecycle_stage: active
name: /Shared/Ultralytics
