artifact_location: file:///C:/Users/ma2mo/Documents/Master/vision/Trabajo-final/UDIT-main/UDIT-main/runs/mlflow/0
creation_time: 1747854309951
experiment_id: '0'
last_update_time: 1747854309951
lifecycle_stage: active
name: Default
